#!/bin/bash 

if [[ ! -z "$ZSH_VERSION" ]]; then 
  setopt SH_WORD_SPLIT
elif [[ ! -z "$BASH_VERSINFO" ]]; then
  if [[ ${BASH_VERSINFO[0]} < 4 ]]; then 
    # try running in ZSH:
    zsh "$0" "$@"
    exit $?
  fi
else
  echo "WARNING: this script is only supported on bash or zsh!"
fi

function usage {
  cat <<'EOD'

This is a no-frills script to compile and link small C++ projects. It emulates
what a Makefile might do, based on simple assumptions:

- all code files have a `.cpp` suffix (no restrictions for headers).

- any code file in the top-level folder that defines a `main()` function is
  destined to produce a corresponding executable of the same name (with the
  `.cpp` suffix stripped out).

- *user* headers are `#include`d in inverted commas, while *system* headers are
  `#include`d in angled brackets, i.e. like this:

        // when working out dependencies:
        #include "my_header.h"   // <- user header: will be inspected
        #include <iostream>      // <- system header: will be ignored

  This is important if the script is to work out dependencies correctly: it will
  scan through all *user* headers recursively to work out whether each object is
  up to date relative to the headers it depends on, but ignore all *system*
  headers.

- any additional `cpp` files that need to be compiled and linked with the
  target executable(s) must have a corresponding header file, with the same
  name (but expected suffix for a header file), and this header must be
  `#include`d in another dependency for that executable (header or cpp). Otherwise,
  the corresponding object file will not be included in the list when linking
  the target executable. 

  For example, if `main.cpp` relies on functionality in `utils.cpp`, then the
  `utils.h` header must exist and be `#include`d by `main.cpp` (or one of the other
  already included headers).

#### Invoking the build script

Make sure your working directory is the folder containing your code, then
simply type `build`. The default action is to build the executables (i.e.
compile the .cpp files and link the resulting objects).

The `build` script accepts these special commands as the first argument:

- `help`:    print this help page
- `clean`:   remove all files (the executable and all objects).

If a different argument is provided, the `build` script will try match it to an
existing build configuration (by default, 'release' or 'debug'). If
unspecified, the `build` script will default to the 'release' configuration.

Available configurations for this project are:

EOD

for config in ${!description[@]}; do
  echo "- \`$config\`: ${description[$config]}"
done

  cat <<'EOD'

The `build` script also accepts the following options:

- `-verbose`: print out additional information about what the script is doing,
              including the executables detected, each intermediate file's
              dependencies, whether why each file needs to be updated, and why.

#### Customising the build

If you need to override the default settings (compiler executable, provide
non-default or additional include locations, etc), place those settings in the
`settings.sh` file. An example such file is provided in the
`settings_example.sh`; you can simply copy this file and name it `settings.sh`,
modify as required, and invoke `build` again.

It is also possible to override some settings using environment variables,
including:

- `CXX`:        override the default compiler (default: `g++`)
- `CXXSTD`:     override the default version of the C++ standard (default:
                `c++17`) 
- `NJOBS`:      override the default number of concurrent compile jobs
                (default: as reported by `nproc`)

For example:

    $ CXX=clang++ NJOBS=4 build


EOD
}





#######################################
# DEFAULT SETTINGS:
#######################################

# set compiler executable:
# use CXX environment variable if set, otherwise default to g++
cxx=${CXX:-g++}

# set default C++ language standard:
std=${CXXSTD:-c++17}

declare -A description
declare -A cflags
declare -A ldflags

# compiler flags used for release build:
description['release']="create build suitable for release"
cflags['release']="-O2 -DNDEBUG"
ldflags['release']=""


# compiler flags used for debug build:
description['debug']="create build suitable for debugging"
cflags['debug']="-D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC -g"
ldflags['debug']="-g"

# command to run to display compiler output on error:
display_error="less -X"

# maximum number of compile jobs to run concurrently:
# default to number of cores on system, as reported by 'nproc'
# or 4 if nproc is not found
njobs=$(nproc) || njobs=4

# override number of jobs using NJOBS environment variable if specified:
njobs=${NJOBS:-$njobs}


#######################################
# START OF SCRIPT PROPER:
#######################################

# terminate script on error:
set -e

clean=0
verbose=0
targets=()
declare -A deps
declare -A headers
declare -A objects

# load user-specific defaults if present:
if [ -f settings.sh ]; then
  . settings.sh
fi

rm -f build_log.txt



#######################################
# FUNCTIONS
#######################################

report() {
  # print to stderr:
  >&2 echo $@
}


error() {
  # print to stderr and exit:
  >&2 echo ERROR: $@
  exit 1
}

debug() {
  if [ ! $verbose -eq 0 ]; then
    report '#' $@
  fi
}


check_need_update() {
  # check whether target ('dest') is older than its dependencies:
  dest=$1
  shift 1

  debug $dest depends on $@

  # target exists?
  if [[ ! -f $dest ]]; then
    debug "- $dest does not exist - needs update"
    return 0
  fi

  # target older than dependencies?
  for n in $@; do
    if [[ $dest -ot $n ]]; then
      debug "- $dest is older than dependency $n - needs update"
      return 0
    fi
  done

  debug "- $dest is already up to date"
  # target is up to date: return non-zero exit code
  return 1
}


compile() {
  j=( $(jobs -rp) )
  while (( ${#j[@]} >= $njobs )); do
    sleep 0.02
    j=( $(jobs -rp) )
  done

  # compile cpp file into object
  cmd="$cxx ${cflags[$config]} -std=$std -I. -c $1 -o ${1%.*}.o"
  report "[CC]" $cmd
  ( 
    if ! $cmd 2> build_log.txt ; then
      $display_error build_log.txt
      return 1
    fi
    [[ -s build_log.txt ]] && cat build_log.txt || :
  ) &
}



link() {
  # link objects into executable
  local exe
  exe=$1
  shift
  cmd="$cxx ${ldflags[$config]} $@ -o $exe"
  report "[LD]" $cmd
  if ! $cmd 2> build_log.txt ; then
    $display_error build_log.txt
    return 1
  fi
  [[ -s build_log.txt ]] && cat build_log.txt || :
}



contains_main() {
  while read line; do
    if [[ "${line%%//*}" =~ int\ *main\ *\(.*\) ]]; then 
      return 0
    fi
  done < $f
  return 1
}



get_targets() {
  # figure out target executable based on which cpp file contains main():
  [[ ${#targets[@]} -gt 0 ]] && return;
  if [[ -z "$ZSH_VERSION" ]]; then 
      shopt -s nullglob
  else
      set -o nullglob
  fi
  for f in *.cpp; do
    contains_main $f && targets+=( "${f%.cpp}" ) || :
  done
}




not_in_list() {
  match="$1"
  shift
  local entry
  for entry in $@; do 
    [[ "$entry" == "$match" ]] && return 1
  done
  return 0
}


get_match () {
  if [[ -z "$ZSH_VERSION" ]]; then 
    f=${BASH_REMATCH[1]} || :
  else
    f=${match[1]} || :
  fi
  echo $f
}


list_local_headers() {
  [[ -z "${headers[$1]}" ]] || return 0
  # list all included local headers:
  # i.e. matching the line '#include "header.h"
  while read line; do
    if [[ "${line%%//*}" =~ ^[[:space:]]*\#[[:space:]]*include[[:space:]]*\"([^\"]*)\" ]]; then 
      f=$(get_match)
      [[ -f $f ]] || error "no such header file \"$f\" (included from file \"$1\")"
      not_in_list $f ${headers[$1]} && headers[$1]+="$f " || :
    fi
  done < $1
}



list_dependencies() {
  [[ -z "${deps[$1]}" ]] || return 0
  # list all dependencies of cpp or h file, including all headers recursively:
  local f
  local h
  list_local_headers $1
  deps[$1]="$1 "
  for f in ${headers[$1]}; do
    not_in_list $f ${deps[$1]} && deps[$1]+="$f " || :
    list_dependencies $f
    for h in ${deps[$f]}; do
      not_in_list $h ${deps[$1]} && deps[$1]+="$h " || :
    done
  done

}



remove_duplicate_objects() {
  local map
  local entry
  declare -A map
  for entry in ${objects[$1]}; do map[$entry]="x"; done
  if [[ -z "$ZSH_VERSION" ]]; then 
    objects[$1]="${!map[@]}"
  else
    objects[$1]="${(@k)map}"
  fi
}



scan_deps_for_target() {
  list_dependencies $1
  local entry
  for entry in ${deps[$1]}; do
    if [[ $entry == *.cpp ]]; then
      list_dependencies $entry
      objects[$exe]="${objects[$exe]} $entry"
    else
      cpp=${entry%.*}.cpp
      [[ -f $cpp ]] || continue
      not_in_list $cpp ${objects[$exe]} || continue
      scan_deps_for_target $cpp
    fi
  done
}




#######################################
# CMDLINE PARSING
#######################################

while [ $# -gt 0 ]; do
  case "$1" in
    "-verbose")
      verbose=1
      ;;
    "help")
      usage
      exit 0
      ;;
    "clean")
      clean=1
      ;;
    *)
      if [[ -z ${cflags["$1"]} ]]; then 
        error "unknown target \"$1\""
        exit 1
      fi
      config="$1"
      ;;
  esac
  shift
done


# default to 'release' build if unspecified:
if [[ -z $config ]]; then
  config=release
fi





#######################################
# MAIN SCRIPT
#######################################

# guess executable names:
get_targets
[[ ${#targets[@]} -lt 1 ]] && report "WARNING: main() not defined in any cpp file - no executables will be generated"

debug "target executables detected: ${targets[@]}"



# recursive scan of included headers to figure out dependency tree:
for exe in ${targets[@]}; do
  scan_deps_for_target $exe.cpp
  remove_duplicate_objects $exe
done


debug using $njobs jobs

# compile and link all targets (unless cleaning), 
# and collate list of temporaries for cleaning:
tmplist=""
if [[ -z "$ZSH_VERSION" ]]; then 
  obj_targets="${!objects[@]}"
else
  obj_targets="${(@k)objects}"
fi


for exe in ${obj_targets}; do
  [[ -f $exe ]] && tmplist+="$exe "
  [[ -f $exe.exe ]] && tmplist+="$exe.exe "
  objlist=""
  for cpp in ${objects[$exe]}; do
    f=${cpp%.*}.o
    [[ -f $f ]] && tmplist+="$f "
    objlist+="$f "
    [[ $clean == 0 ]] && check_need_update ${cpp%.*}.o ${deps[$cpp]} && compile $cpp
  done
  wait $(jobs -p)
  [[ $clean == 0 ]] && check_need_update $exe $objlist && link $exe $objlist
done


# if cleaning, remove all temporaries:
if [[ $clean == 1 ]]; then
  rm -vf $tmplist
  exit 0
fi

